import { AnimateLifecycleProps } from './types'

/**
 * Animation options that are supported in `motion/mini`.
 * @see https://motion.dev/docs/feature-comparison
 */
export const SUPPORTED_OPTIONS = {
  autoplay: 1,
  bounce: 1,
  bounceDamping: 1,
  bounceStiffness: 1,
  damping: 1,
  delay: 1,
  delayChildren: 1,
  driver: 1,
  duration: 1,
  ease: 1,
  elapsed: 1,
  from: 1,
  isSync: 1,
  mass: 1,
  max: 1,
  min: 1,
  modifyTarget: 1,
  onComplete: 1,
  onStop: 1,
  power: 1,
  repeat: 1,
  repeatType: 1,
  restDelta: 1,
  restSpeed: 1,
  staggerChildren: 1,
  staggerDirection: 1,
  startTime: 1,
  stiffness: 1,
  timeConstant: 1,
  times: 1,
  type: 1,
  velocity: 1,
  visualDuration: 1,
  when: 1,
}

export const LIFECYCLE_PROPS = {
  initial: 1,
  enter: 1,
  leave: 1,
  update: 1,
  whileFocus: 1,
  whileHover: 1,
  whilePress: 1,
} satisfies Record<keyof AnimateLifecycleProps, 1>

export const DIGIT_REGEX = /\d+/

export const AMBIGUOUS_LITERALS = {
  inherit: 1,
  initial: 1,
  revert: 1,
  unset: 1,
  auto: 1,
  none: 1,
}

export const COLOR_PROPS = {
  accentColor: 1,
  backgroundColor: 1,
  borderColor: 1,
  caretColor: 1,
  color: 1,
  columnRuleColor: 1,
  fill: 1,
  floodColor: 1,
  lightingColor: 1,
  outlineColor: 1,
  scrollbarColor: 1,
  stopColor: 1,
  stroke: 1,
  textDecorationColor: 1,
  textEmphasisColor: 1,
}

export const NON_ANIMATABLE_PROPS = {
  alignContent: 1,
  alignItems: 1,
  alignSelf: 1,
  appearance: 1,
  boxSizing: 1,
  clear: 1,
  cursor: 1,
  direction: 1,
  display: 1,
  flexDirection: 1,
  flexWrap: 1,
  float: 1,
  fontStyle: 1,
  fontVariant: 1,
  justifyContent: 1,
  justifyItems: 1,
  justifySelf: 1,
  listStyle: 1,
  listStyleType: 1,
  overflow: 1,
  overflowWrap: 1,
  pointerEvents: 1,
  position: 1,
  resize: 1,
  textAlign: 1,
  textDecoration: 1,
  textOverflow: 1,
  textTransform: 1,
  unicodeBidi: 1,
  userSelect: 1,
  verticalAlign: 1,
  visibility: 1,
  whiteSpace: 1,
  wordBreak: 1,
  wordWrap: 1,
  writingMode: 1,
}
